python gen_valid_hdf5.py \
    --data_dir=/media/x6850/DataI1/AIC \
    --train_ann_dir=annotations/person_keypoints_train2017_part1.json \
    --train_img_dir=train2017_part1 \
    --valid_ann_dir=annotations/person_keypoints_valid2017.json \
    --valid_img_dir=valid2017 \
    --train_hdf5_path=train_dataset.h5 \
    --valid_hdf5_path=valid_dataset.h5 \
    --valid_size=30000 \
    --joint_num=14 \
    --log_path=hdf5.log